export const QK = {
  ROUTINE_LIST: 'ROUTINE_LIST',
  EXERCISE_LIST: 'EXERCISE_LIST',
  ROUTINE_HISTORY_EXERCISE_VOLUME: 'ROUTINE_HISTORY_EXERCISE_VOLUME',
  ROUTINE_HISTORY_EXERCISE_DAILY_SUMMARY_LIST: 'ROUTINE_HISTORY_EXERCISE_DAILY_SUMMARY_LIST',
} as const;
